library(arules)
plants <-read.transactions("plants.csv", sep = ",")
summary(plants)
itemFrequencyPlot(plants, support = 0.15)
itemFrequencyPlot(plants, topN = 20)
apriori(plants)
freq_is <- apriori(plants, parameter = list(target = "frequent itemsets", support=0.0731))
inspect(sort(freq_is, by="support"))
inspect(sort(freq_is, decreasing=FALSE,by="support"))
name_rule <-apriori(plants,parameter = list(support=0.1, confidence=0.1,minlen=2 ))
summary(name_rule)
inspect(sort(name_rule, by="confidence"))
inspect(sort(name_rule, by="lift"))
inspect(sort(name_rule, by="support"))